### ISSUE TITLE
tonka

### ISSUE THREAD

**Issue by bhopped** [cliphdd/TikTok-Private-API#1]
Pockets way to fat pockets way to (oh oh oh!)(dub!)
Whole lotta cheese yeah double stuffed
Both them bitches got an ass yeah double fudge
I been shipping gas got these doubles up (yuh)
Everytime I make money yeah double it
(yeah!)(lets go!)
Before we get to fuckin she be suckin it (yee!)
She like the way i talk ,my word, she run with it (yuh)(yea!)
Catch that lil bum with money? , boy jus bum a cig*?
Off the X and perc gone fuck this bitch for 60 days (yee!)
We fucked so long my balls turned purple yеah look like a fig
(yea) we ain't worriеd bout nothin twizzy keep a SIG
Heard their side been getting money but i bet its not like that
They spend their stimulus (yea)

**Comment by cliphdd** [comment]
xmr youre fatherless and you lost all your friends

**Comment by bhopped** [comment]
i didn't lose all my friends and i have a father :D

**Comment by cliphdd** [comment]
im your friend and your daddy so i guess youre right

**Comment by bhopped** [comment]
uhm
